In [1]:
import math

In [2]:
import numpy

###### array

In [10]:
import numpy as np
array1 = np.array([1,2,3])
array2 = np.array([[1,2,3],
                   [4,5,6]])
array1


array([1, 2, 3])

In [14]:
[1,2,3] * [4,5,6]

TypeError: can't multiply sequence by non-int of type 'list'

In [12]:
array1 = np.array([1,2,3])
array3 = np.array([4,5,6])

In [15]:
array1*array3

array([ 4, 10, 18])

In [16]:
# 차원 알아보기

array1.shape

(3,)

In [17]:
array2.shape

(2, 3)

In [65]:
ndarray = np.array([[[[1,2,3.5],
 [4,5,6]],
[[7,8,9],
 [10,11,12]]]])

In [67]:
ndarray.ndim

4

In [55]:
ndarray.dtype

dtype('float64')

In [34]:
ndarray.astype('float64')

array([[[ 1. ,  2. ,  3.5],
        [ 4. ,  5. ,  6. ]],

       [[ 7. ,  8. ,  9. ],
        [10. , 11. , 12. ]]])

numpy.zeros(shape, dtype=float, order='C', *, like=None)

In [50]:
# zeros() 메소드

np.zeros(10)+10

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

In [51]:
ndarray = np.ones((2 ,5),dtype=int)*2

In [52]:
ndarray.shape

(2, 5)

###### mean()
numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)[[source\]](https://github.com/numpy/numpy/blob/v1.21.0/numpy/core/fromnumeric.py#L3322-L3441)

In [68]:
a = np.array([[1, 2], [3, 4]])
np.mean(a)

2.5

In [69]:
np.mean(a , axis=0)

array([2., 3.])

In [70]:
np.mean(a , axis=1)

array([1.5, 3.5])

##### reshape
numpy.reshape(a, newshape, order='C')

In [74]:
a = np.arange(6).reshape((2, 3))

In [75]:
a

array([[0, 1, 2],
       [3, 4, 5]])

###### sqrt
numpy.sqrt(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'sqrt'>

In [78]:
import math

math.sqrt([1,2,3])

TypeError: must be real number, not list

In [79]:
np.sqrt(np.array([1,2,3]))

array([1.        , 1.41421356, 1.73205081])

###### transpose()
numpy.transpose(a, axes=None)

In [83]:
x = np.arange(12).reshape((4,3))
np.transpose(x)

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [3]:
a = np.array([10, 20, 30, 40, 50, 60, 70])
b = np.array(a[1:6:2])
print('b:', b)
b[1] = 10
print('b:', b)
print('a:', a)
type(b)

b: [20 40 60]
b: [20 10 60]
a: [10 20 30 40 50 60 70]


numpy.ndarray

##### np.random

###### linspace
* numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)[source]

In [15]:
arr_1 = np.linspace(0, 12, num=4)
arr_2 = np.linspace(0, 12, 4, retstep=True)
arr_3 = np.linspace(0, 12, 4, False , True)

In [16]:
print(arr_1 ,arr_2 , arr_3 )

[ 0.  4.  8. 12.] (array([ 0.,  4.,  8., 12.]), 4.0) (array([0., 3., 6., 9.]), 3.0)


###### logspace
numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)

###### random.rand()
random.rand(d0, d1, ..., dn)

In [25]:
np.random.seed(10)
np.random.rand(5)
# np.random.rand(2,3)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701])

In [29]:
np.random.rand(10,5)

array([[0.67413362, 0.44183317, 0.43401399, 0.61776698, 0.51313824],
       [0.65039718, 0.60103895, 0.8052232 , 0.52164715, 0.90864888],
       [0.31923609, 0.09045935, 0.30070006, 0.11398436, 0.82868133],
       [0.04689632, 0.62628715, 0.54758616, 0.819287  , 0.19894754],
       [0.8568503 , 0.35165264, 0.75464769, 0.29596171, 0.88393648],
       [0.32551164, 0.1650159 , 0.39252924, 0.09346037, 0.82110566],
       [0.15115202, 0.38411445, 0.94426071, 0.98762547, 0.45630455],
       [0.82612284, 0.25137413, 0.59737165, 0.90283176, 0.53455795],
       [0.59020136, 0.03928177, 0.35718176, 0.07961309, 0.30545992],
       [0.33071931, 0.7738303 , 0.03995921, 0.42949218, 0.31492687]])

##### numpy.random.randn
* random.randn(d0, d1, ..., dn)
* Return a sample (or samples) from the “standard normal” distribution.